# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/test/out
.PHONY: all
all:
	$(MAKE) -C ../.. field_trial video_test_common rtp_test_utils channel_transport test_support test_support_main_threaded_mac test_support_main test_renderer test_main test_common test_support_unittests test_support_unittests_run
