# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/voice_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. voice_engine voe_auto_test voe_auto_test_run voice_engine_unittests voice_engine_unittests_run voe_cmd_test
