# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/system_wrappers/out
.PHONY: all
all:
	$(MAKE) -C ../.. metrics_default field_trial_default system_wrappers system_wrappers_default
