# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/tools/out
.PHONY: all
all:
	$(MAKE) -C ../.. agc_test_utils video_quality_analysis psnr_ssim_analyzer frame_analyzer rgba_to_i420_converter frame_editing_lib frame_editor rtp_analyzer activity_metric tools_unittests tools_unittests_run force_mic_volume_max audio_e2e_harness agc_harness
