# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/common_audio/out
.PHONY: all
all:
	$(MAKE) -C ../.. common_audio_sse2 common_audio common_audio_unittests common_audio_unittests_run
